# deploy/overlays/green/kustomization.yaml   ? igual pero green
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

nameSuffix: -green
labels:
  - pairs:
      version: green