# deploy/overlays/green/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/deployment.yaml   # ? SOLO el deployment

nameSuffix: -green

commonLabels:
  version: green

patches:
  - target:
      kind: Deployment
    patch: |
      - op: replace
        path: /metadata/labels/version
        value: green
      - op: replace
        path: /spec/template/metadata/labels/version
        value: green
      - op: replace
        path: /spec/selector/matchLabels/version
        value: green