resources:
  - ../../base

namespace: default

nameSuffix: -green

images:
  - name: freddych/5ud03r5app
    newName: freddych/5ud03r5app
    newTag: latest

patches:
  - target:
      kind: Deployment
    patch: |
      - op: replace
        path: /metadata/labels/version
        value: green
      - op: replace
        path: /spec/template/metadata/labels/version
        value: green
      - op: replace
        path: /spec/selector/matchLabels/version
        value: green