# deploy/overlays/green/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - -service.yaml
  - -ingress.yaml

nameSuffix: -green

labels:
  - pairs:
      version: green