# deploy/overlays/green/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

nameSuffix: -green

labels:
  - pairs:
      version: green

patches:
  - target:
      kind: Deployment
    patch: |
      - op: replace
        path: /spec/selector/matchLabels/version
        value: green
      - op: replace
        path: /spec/template/metadata/labels/version
        value: green