apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

nameSuffix: -green
commonLabels:
  version: green
replicas:
  - name: app-blue
    count: 2
patches:
  - target:
      kind: Deployment
      name: app-blue
    patch: |
      - op: replace
        path: /metadata/name
        value: app-green