# deploy/base/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: app-service             # ← nombre fijo y único
  labels:
    app: 5ud03r5app
spec:
  type: LoadBalancer            # o NodePort en Minikube
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: 5ud03r5app
    version: blue               # ← valor inicial (luego se cambia con patch)