apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-VERSION
  labels:
    app: 5ud03r5app
    version: VERSION
spec:
  replicas: 2
  selector:
    matchLabels:
      app: 5ud03r5app
      version: VERSION
  template:
    metadata:
      labels:
        app: 5ud03r5app
        version: VERSION
    spec:
      containers:
      - name: app
        image: freddych/5ud03r5app:IMAGE_TAG
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: app-service-VERSION
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: 5ud03r5app
    version: VERSION
