# deploy/overlays/production/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../blue
  - ../green
  - ../../base/service.yaml     # único Service
  - ingress.yaml                # ← el Ingress único

images:
  - name: freddych/5ud03r5app
    newName: freddych/5ud03r5app
    newTag: 1-0-10

patches:
  - target:
      kind: Service
      name: app-service
    patch: |
      - op: replace
        path: /spec/selector/version
        value: blue