apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployments/deployment-blue.yaml
  - deployments/deployment-green.yaml
  - services/service.yaml
  - ingress/ingress.yaml

# Definimos la versión de la imagen que quieres desplegar
images:
  - name: freddych/5ud03r5app
    newTag: 1-0-34   # <-- Cambia este valor según la versión que quieras

configMapGenerator:
  - name: active-env
    literals:
      - active=blue   # Valor inicial, indica cuál entorno está activo
