# deploy/overlays/production/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../blue
  - ../green

# ← ESTA ES LA LÍNEA QUE FALTABA (OBLIGATORIA)
images:
  - name: freddych/5ud03r5app
    newName: freddych/5ud03r5app   # ← imprescindible
    newTag: 1-0-11                 # ← esta es la que cambias cada vez

# Tráfico inicial (puedes cambiarlo después con kubectl patch o en la UI)
patches:
  - target:
      kind: Service
      name: app-service
    patch: |
      - op: replace
        path: /spec/selector/version
        value: green   # o blue, como prefieras