apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/deployment.yaml
  - ../../base/service.yaml
  - ingress.yaml

# Generamos blue
nameSuffix: -blue
commonLabels:
  version: blue

# Generamos green duplicando el deployment
replicas:
  - name: app-blue
    count: 2

# Componente que crea green
components:
  - components/green.yaml

images:
  - name: freddych/5ud03r5app
    newName: freddych/5ud03r5app
    newTag: 1-0-26

# Tr√°fico inicial a blue
patches:
  - target:
      kind: Service
      name: app-service
    patch: |
      - op: replace
        path: /spec/selector/version
        value: blue