resources:
  - ../blue
  - ../green
  - ../../base/service.yaml     # ← el único Service
  - ../../base/ingress.yaml     # ← el único Ingress (si lo usas)

images:
  - name: freddych/5ud03r5app
    newName: freddych/5ud03r5app
    newTag: 1-0-16

patches:
  - target:
      kind: Service
      name: app-service
    patch: |
      - op: replace
        path: /spec/selector/version
        value: blue