apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# Blue deployment activo
commonLabels:
  version: blue
replicas:
  - name: app
    count: 2

# Green deployment para nueva versi√≥n
components:
  - components/green

# Imagen actualizada por ArgoCD Image Updater
images:
  - name: freddych/5ud03r5app
