apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../blue
  - ../green
  - ../../base/service.yaml     # ← el único Service
  - ../../base/ingress.yaml     # ← si lo tienes

images:
  - name: freddych/5ud03r5app
    newName: freddych/5ud03r5app
    newTag: 1-0-19               # ← cambias solo esta línea

patches:
  - target:
      kind: Service
      name: app-service
    patch: |
      - op: replace
        path: /spec/selector/version
        value: blue                 # tráfico inicial