apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployments/deployment-blue.yaml
  - deployments/deployment-green.yaml
  - services/service.yaml
  - ingress/ingress.yaml

configMapGenerator:
  - name: active-env
    literals:
      - active=blue   # Valor inicial del entorno activo

replacements:
  - source:
      kind: ConfigMap
      name: active-env
      fieldPath: data.active
    targets:
      - select:
          kind: Service
        fieldPaths:
          - spec.selector.version
        options:
          create: false
