apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../blue
  - ../green
  - ingress.yaml                 # ← el único Ingress

images:
  - name: freddych/5ud03r5app
    newName: freddych/5ud03r5app
    newTag: 1-0-23

patches:
  - target:
      kind: Service
      name: app-service
    patch: |
      - op: replace
        path: /spec/selector/version
        value: blue