# deploy/overlays/blue/kustomization.yaml   ? VUELVE A ESTO (funciona)
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base                 # ? carpeta completa

nameSuffix: -blue
labels:
  - pairs:
      version: blue