# deploy/overlays/blue/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/deployment.yaml   # ? SOLO el deployment

nameSuffix: -blue

labels:
  - pairs:
      version: blue