apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    app: 5ud03r5app
spec:
  selector:
    app: 5ud03r5app
    version: blue  # Inicialmente apunta a blue
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer
